language: rust
sudo: false

matrix:
  fast_finish: true
  include:
    - rust: 1.31.0
    - rust: stable
    - rust: beta
    - rust: nightly

branches:
  only:
    - master
    - staging
    - trying
